# Site
name: "Spatial Biology Association"
title: "Spatial Biology Association"
description: "Advancing the science and application of spatial biology!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /sba
google_analytics: ''
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: ajitjohsnon.n@gmail.com

# Authors
authors:
  sal:
    name: Ajit Johnson Nirmal
    display_name: Ajit
    avatar: 'assets/images/avatar-sal.png'
    email: ajitjohsnon.n@gmail.com
    web: https://ajitjohnson.com/
    twitter: https://twitter.com/ajitjohnson_n
    description: Cancer Geneticist @harvard

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
